export const SET_USER_INFO = 'SET_USER_INFO';
export const SET_FOUND = 'SET_FOUND';

export const SET_CLEAR = 'SET_CLEAR';
export const SET_CLEAR_ALBUM = 'SET_CLEAR_ALBUM';

export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_FAIL = 'FETCH_FAIL';

export const FETCH_ARTIST_ALBUMS_SUCCESS = 'FETCH_ARTIST_ALBUMS_SUCCESS';
export const FETCH_ARTIST_ALBUMS_FAIL = 'FETCH_ARTIST_ALBUMS_FAIL';

export const FETCH_ALBUM_SUCCESS = 'FETCH_ALBUM_SUCCESS';
export const FETCH_ALBUM_FAIL = 'FETCH_ALBUM_FAIL';

export const FETCH_ARTIST_TRACKS_SUCCESS = 'FETCH_ARTIST_TRACKS_SUCCESS';
export const FETCH_ARTIST_TRACKS_FAIL = 'FETCH_ARTIST_TRACKS_FAIL';

// export const FETCH = 'SET_FOUND';
export const DELETE_SEARCH = 'DELETE_SEARCH';

// export const SET_FOUND_ARTISTS = 'SET_FOUND_ARTISTS';
// export const SET_FOUND_PLAYLISTS = 'SET_FOUND_PLAYLISTS';
// export const SET_FOUND_ALBUMS = 'SET_FOUND_ALBUMS';

